In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pathlib

In [127]:
x=pd.Series(np.linspace(1,100,20),index=np.arange(0,191,10))
x

0        1.000000
10       6.210526
20      11.421053
30      16.631579
40      21.842105
50      27.052632
60      32.263158
70      37.473684
80      42.684211
90      47.894737
100     53.105263
110     58.315789
120     63.526316
130     68.736842
140     73.947368
150     79.157895
160     84.368421
170     89.578947
180     94.789474
190    100.000000
dtype: float64

In [131]:
x.index

Index([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190],
      dtype='int64')

In [119]:
x.values

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [149]:
x[20]=54

In [153]:
x.describe()

count     20.000000
mean      52.628947
std       29.423327
min        1.000000
25%       30.960526
50%       53.552632
75%       75.250000
max      100.000000
dtype: float64

In [155]:
x.info()

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 190
Series name: None
Non-Null Count  Dtype  
--------------  -----  
20 non-null     float64
dtypes: float64(1)
memory usage: 876.0 bytes


In [6]:
df=pd.read_csv(path,delimiter='\t')

In [8]:
df.head()

Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave   
1      1  526301100           20        RL         141.0     31770   Pave   
2      2  526350040           20        RH          80.0     11622   Pave   
3      3  526351010           20        RL          81.0     14267   Pave   
4      4  526353030           20        RL          93.0     11160   Pave   

  Alley Lot Shape Land Contour  ... Pool Area Pool QC  Fence Misc Feature  \
0   NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
1   NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
2   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
3   NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
4   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

  Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice  
0        0       5    2010       WD           Normal     215000  
1        0       5    2010       WD           Normal     215000  
2        0       6    2010       WD           Normal     105000  
3    12500       6    2010       WD           Normal     172000  
4        0       4    2010       WD           Normal     244000  

[5 rows x 82 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2931 entries, 0 to 2930
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Order            2931 non-null   int64  
 1   PID              2931 non-null   int64  
 2   MS SubClass      2931 non-null   int64  
 3   MS Zoning        2931 non-null   object 
 4   Lot Frontage     2441 non-null   float64
 5   Lot Area         2931 non-null   int64  
 6   Street           2931 non-null   object 
 7   Alley            198 non-null    object 
 8   Lot Shape        2931 non-null   object 
 9   Land Contour     2931 non-null   object 
 10  Utilities        2931 non-null   object 
 11  Lot Config       2931 non-null   object 
 12  Land Slope       2931 non-null   object 
 13  Neighborhood     2931 non-null   object 
 14  Condition 1      2931 non-null   object 
 15  Condition 2      2931 non-null   object 
 16  Bldg Type        2931 non-null   object 
 17  House Style   

In [26]:
df.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ... 
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

In [14]:
x=12,13
x

(12, 13)

In [16]:
y=list(x)
y

[12, 13]

In [20]:
y[1]=19
y

[12, 19]

In [22]:
x=tuple(y)
x

(12, 19)

In [72]:
l=np.array([[[2,3],[2,5]]])
l

array([[[2, 3],
        [2, 5]]])

In [70]:
l.ndim

3

In [109]:
x=np.arange(1,100,16)
x

array([ 1, 17, 33, 49, 65, 81, 97])

In [98]:
x=np.linspace(1,10,100)
x

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [167]:
df=pd.DataFrame([[1810,'Moin',3.48],[1774,'Saif',3.46],[1805,'Irfan','F'],[1776,'Zawyan',3.30]],index=[1,2,3,4] ,columns=['Roll No.','Name','CGPA'] )
df

Roll No.    Name  CGPA
1      1810    Moin  3.48
2      1774    Saif  3.46
3      1805   Irfan     F
4      1776  Zawyan   3.3

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Roll No.  4 non-null      int64 
 1   Name      4 non-null      object
 2   CGPA      4 non-null      object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes


In [187]:
type_counts = df['CGPA'].apply(lambda x: type(x)).value_counts()
print(type_counts)

CGPA
<class 'float'>    3
<class 'str'>      1
Name: count, dtype: int64


In [189]:
def f(x):
    return x**2

In [191]:
f(2)

4

In [193]:
lambda x:x**2

<function __main__.<lambda>(x)>

In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame([['Alice',25,'female'],['Bob',35,'male'],['Charlie',40,'male']], columns=['Name','Age','Gender'],index=[1,2,3])
df

Name  Age  Gender
1    Alice   25  female
2      Bob   35    male
3  Charlie   40    male

In [2]:
df['city']=['new york','italy','france']
df

Name  Age  Gender      city
1    Alice   25  female  new york
2      Bob   35    male     italy
3  Charlie   40    male    france

In [5]:
df.columns

Index(['Name', 'Age', 'Gender', 'city'], dtype='object')

In [6]:
df.index

Index([1, 2, 3], dtype='int64')

In [19]:
a=df.loc[2]
b=df.iloc[2]
c=df['city']

print(a, "\n", b, "\n", c)

Name        Bob
Age          35
Gender     male
city      italy
Name: 2, dtype: object 
 Name      Charlie
Age            40
Gender       male
city       france
Name: 3, dtype: object 
 1    new york
2       italy
3      france
Name: city, dtype: object
