In [9]:
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
%matplotlib inline

In [3]:
x=np.arange(1,101)
y=np.array([99,99,11,11,11])
x=np.concatenate((x,y))
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100,  99,  99,  11,  11,
        11])

In [4]:
#Descriptive Stats:
mode=stats.mode(x)
print(f'Measures of Centeral Tendency:\nMean(tells about average value)={np.mean(x)}\nMedian(tells about middle most value in ascending order sorted values)={np.median(x)}\nMode(tells about most repeated (frequent) value value)={mode}')

Measures of Centeral Tendency:
Mean(tells about average value)=50.2952380952381
Median(tells about middle most value in ascending order sorted values)=50.0
Mode(tells about most repeated (frequent) value value)=ModeResult(mode=11, count=4)


In [5]:
print(f'Min Value={np.min(x)}\nMax Value={np.max(x)}\nVariance(tells us about variations in data)={np.var(x)}\nStand. Dev.(deviation of data from)={np.std(x)}')

Min Value=1
Max Value=100
Variance(tells us about variations in data)=882.9128344671202
Stand. Dev.(deviation of data from)=29.71384920314297


In [36]:
#Random Numbers:
r=np.random.rand(4, 2, 3) #generates uniformly distributed floating-point numbers in the half-open interval [0, 1) (i.e., 0.0 is a possible outcome, but 1.0 is not).
r

array([[[0.40526019, 0.33153101, 0.16225637],
        [0.05370176, 0.49114347, 0.07716017]],

       [[0.68845872, 0.37522947, 0.81308323],
        [0.12953465, 0.19975772, 0.91070374]],

       [[0.79824703, 0.70559639, 0.38435269],
        [0.4381067 , 0.92624074, 0.98662244]],

       [[0.77912029, 0.7689028 , 0.94786088],
        [0.53357131, 0.14513722, 0.27384789]]])

In [38]:
r=np.random.randn(20 ,2) # generates random numbers that are distributed according to the standard normal distribution (the normal distribution with mean 0 and standard deviation 1)
r

array([[-0.91922678,  0.93242536],
       [-2.4056653 , -1.50685404],
       [ 0.03711596,  2.13777893],
       [ 0.54053316, -0.37194821],
       [-0.0672052 ,  0.87126474],
       [-0.45496617, -0.84351787],
       [-0.40840852,  0.83910657],
       [-0.13072264,  0.29531629],
       [ 0.06867006,  0.95243472],
       [ 0.37883258,  0.79995953],
       [ 1.98877973,  0.06535878],
       [ 0.76910512, -1.9078561 ],
       [-1.27046172, -0.2049415 ],
       [ 0.13996496,  0.94047715],
       [ 0.56599006,  0.06696787],
       [ 2.92949424,  0.37531134],
       [ 0.37733137, -0.46646498],
       [ 0.35540717,  0.86971427],
       [-1.53152836,  0.23204367],
       [ 1.37139325,  1.3383453 ]])

In [44]:
r=np.random.randint(2, 7, [2,2]) #generates uniformly distributed integers between a given low (inclusive) and high(exclusive) value.
r

array([[5, 3],
       [5, 4]])

In [ ]:
filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
df = pd.read_csv(filepath, header=None)

In [ ]:
df.head()

In [ ]:
df.columns=["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [ ]:
df.head()